package com.parvez.android.storage;

import org.springframework.core.io.Resource;
import java.io.IOException;
import java.io.InputStream;

/**
 * Internal byte-storage boundary. Callers authorize access and validate document content.
 * Keys are opaque and generated by storage, never client filenames or paths.
 * Implementations must stream bytes and remove partial uploads on failure.
 */
public interface FileStorageService {
    String provider();
    /** Does not close the caller's input. Enforces a positive byte limit while streaming. */
    StoredFile upload(InputStream input, long maximumBytes) throws IOException;
    /** Returns a repeatable resource; callers close each opened stream. Never expose its path. */
    Resource download(String key) throws IOException;
    /** Deleting a missing valid key succeeds. */
    void delete(String key) throws IOException;
    boolean exists(String key);
    record StoredFile(String key, long size, String checksum) {}
}
