CREATE TABLE books
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn             VARCHAR(20)  NOT NULL,
    title            VARCHAR(255) NOT NULL,
    author           VARCHAR(255) NOT NULL,
    publication_date VARCHAR(20)  NOT NULL,
    description      TEXT,
    completed        BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uk_books_isbn UNIQUE (isbn)
);
